### ISSUE TITLE
Getting error while trying to save item from auto generated add view of model.

### ISSUE THREAD

**Issue by fusionstrings** [chiefy/sails-generate-frontend-angular#1]
Hi,
I followed the instructions on http://chiefy.github.io/2014/06/24/using-sails-generate-frontend-angular.html .

All is well but when I am trying to save item it's giving following error.

![image](https://cloud.githubusercontent.com/assets/450624/3438584/ece6bad8-00cb-11e4-9fd6-4eacd62b99d3.png)

**Comment by chiefy** [comment]
@fusionstrings I am going to need to see more of your code in order to figure out what the issue is. 

Can you post your model / controller / view?

**Comment by fusionstrings** [comment]
@chiefy here I've uploaded entire app. It's basically default generated app, after literally following steps on http://chiefy.github.io/2014/06/24/using-sails-generate-frontend-angular.html

**Comment by chiefy** [comment]
@fusionstrings did you forget to link to the code? If you're following the example on my blog, we don't generate a `Product` class, so you might need to `sails generate api product` before you can try to do anything with that route.

**Comment by fusionstrings** [comment]
@chiefy Ohh sorry about it. Here it is https://github.com/fusionstrings/ngSailsApp, which I believe you have found out.

I'd run that command already `sails generate api product`. and that's how I got add product page. It's after entering value it's not saving and giving above error. 

P.S. I just followed instructions and didn't setup any DB.

**Comment by chiefy** [comment]
@fusionstrings it looks like you did `sails generate api products`, note you used the plural. You need to `sails generate api product` otherwise Sails has no idea what the plural of `products` is and just uses `products` as the singular _and_ plural. Let me know if that helps you out.

**Comment by fusionstrings** [comment]
Yes, indeed it was the case. Thanks for pointing it out. :100:

**Comment by chiefy** [comment]
@fusionstrings I might try to work in a warning when you specify a model name that isn't in the singular, might help people in the future. Thanks!

**Comment by fusionstrings** [comment]
:+1:
